### ISSUE TITLE
Pre-trained PubDef model for ImageNet

### ISSUE THREAD

**Issue by ZhengyuZhao** [wagner-group/pubdef#1]
Hi Chawin, 

Nice to see this impressive work! 
It seems that the pre-trained PubDef model for ImageNet has not been released yet. Is it possible to get it?

Best,
Zhengyu

**Comment by chawins** [comment]
Thank you for taking a look at our work! As requested, I updated the evaluation script (https://github.com/wagner-group/pubdef?tab=readme-ov-file#evaluation-script) and put up the pretrained models and some example attacks (for CIFAR-10/100 and ImageNet) at https://www.kaggle.com/datasets/csitawarin/pubdef-defending-against-transfer-attacks/. Please let us know if you run into any trouble with the code, the files, or anything else!

**Comment by ZhengyuZhao** [comment]
> Thank you for taking a look at our work! As requested, I updated the evaluation script (https://github.com/wagner-group/pubdef?tab=readme-ov-file#evaluation-script) and put up the pretrained models and some example attacks (for CIFAR-10/100 and ImageNet) at https://www.kaggle.com/datasets/csitawarin/pubdef-defending-against-transfer-attacks/. Please let us know if you run into any trouble with the code, the files, or anything else!

Many thanks for the updates!

**Comment by ZhengyuZhao** [comment]
Another small question:

Where can I find the details about the L_inf norms you have used for training (PubDef) and testing on ImageNet?
I can only find the one for testing from https://github.com/wagner-group/pubdef/blob/main/scripts/example_test.sh#L26

Thanks!

**Comment by chawins** [comment]
Ah, thank you for catching that!

The numbers in the script are accurate, i.e., 8/255 for CIFAR-10 and CIFAR-100 and 4/255 for ImageNet.
